keys:
  - &main_workstation age1zdvyc7f5953tvnw266z7799n43vk8kq58ykkudgkp704e05qs3hsc93gu7
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *main_workstation
